### PR TITLE
Release 0.17.0

### PR DESCRIPTION
**Pull request by r3nic1e**

### CODE REVIEW

**Comment by zhilyaev** [comment]
tests?

**Comment by r3nic1e** [comment]
> tests?

Yep, I know. The PR is still in draft :)

**Comment by zhilyaev** [comment]
This PR is so big :)

**Comment by zhilyaev** [comment]
@helmwave/maintainers check team notify)

**Comment by zhilyaev** [comment]
linter)

**Comment by zhilyaev** [comment]
pick up https://github.com/helmwave/helmwave/issues/236

**Comment by r3nic1e** [comment]
I guess we wait for #236 and good to go.
By the way I've changed codecov.yml here. So It shows reducing coverage while that's not true because of old tests carryforward. So that's okay.

**Review by zhilyaev — APPROVED** [review]

**Pull request merged**
