### PR TITLE
Release/0.32.2

### PR DESCRIPTION
**Pull request by zhilyaev**

### CODE REVIEW

**Comment by zhilyaev** [comment]
@anuragagarwal561994 could you write changelog for us with `changie`?

**Comment by anuragagarwal561994** [comment]
@zhilyaev I have added a pull request to add the changelog

**Comment by zhilyaev** [comment]
I need to fix the tests , and release will ready

**Comment by anuragagarwal561994** [comment]
@zhilyaev I have already added MRs for fixing these tests

**Comment by anuragagarwal561994** [comment]
https://github.com/helmwave/helmwave/pull/762

I think if possible we can also include:
https://github.com/helmwave/helmwave/pull/757
https://github.com/helmwave/helmwave/pull/755

in this release, everything from side seems ready here

**Pull request merged**
