### PR TITLE
Add support for using .env file

### LINKED ISSUE #750: Add support to use dotenv file
**Is your feature request related to a problem? Please describe.**
Since most of the flags are backed by env variables it will be easier to use and commit them with dotenv file

**Describe the solution you'd like**
Using dotenv file to read env variables

I have tried using tools such as direnv, autoenv, zsh configurations etc. but to be honest it is very cumbersome to configure and deal with them, although they would work but the biggest questions for such tools is that if we have configured some envs when a user enters a directory how will we unset them when user exits the directory and that does create an .env mess. Hence a better solution is always to adopt the application itself to add support for reading .env files.

### PR DESCRIPTION
**Pull request by anuragagarwal561994**
Closes #750

### CODE REVIEW

**Comment by anuragagarwal561994** [comment]
I have tested the changes on my local machine and they work, but I am not sure how to write a test case for the same. Any suggestions would help

**Comment by zhilyaev** [comment]
@anuragagarwal561994 could you describe use-cases? I don't understand what you need.

**Comment by zhilyaev** [comment]
`source <(cat .env)` looks like that enough

**Comment by anuragagarwal561994** [comment]
helmwave supports providing almost everything via command line flags as well as env variables. The idea is to keep to use the .env files so that one can commit these changes to their repository and is consistently accessed across.

There exists some solution like you mentioned above to populate current shell with the env variables, but it makes the user shell env dirty, like if I am switching to another project using helmwave then some of the variables from the old project will still be applied because it is difficult to clear them, without tracking what were the earlier env variables. 

Hence it is better to use .env file so it remains applicable for a project and doesn't pollute the user shell environement, saves one extra step when entering a project directory.

**Comment by anuragagarwal561994** [comment]
@zhilyaev one more thing to add here, I tried the above command that you mentioned it was not working.

I used an alternative option `direnv` but the issue again is everytime I make changes in the .env file I have to execute an extra command `direnv allow`, and I have tried several other mechanisms like autoenv etc. and they are kind of behave in the same way.

Using .env seems very easy and convinient as it is restricted to only the project folder.

**Comment by anuragagarwal561994** [comment]
I hope I don't have to do anything with respect to the gitleaks failing action?

**Comment by zhilyaev** [comment]
I don't think it will be good.

1. Unexpected behavior when somebody needs to define env variables.
2. Another file is just a config. Why can't we use viper or similar things? Cause it's not config. Config is `helmwave.yml`.
3. godotenv looks like mis conception of usage for regular users.

**Comment by zhilyaev** [comment]
> I hope I don't have to do anything with respect to the gitleaks failing action?

don't worry it's just lose token for outside contributors users. I've already disabled it for all branches.

**Comment by anuragagarwal561994** [comment]
> 2. Another file is just a config. Why can't we use viper or similar things? Cause it's not config. Config is `helmwave.yml`.

So actually there is a very clear difference between the two because of which I had to implement this feature.

so helmwave.yml is configuring the helm part and .env is configuring helmwave and this is is super helpful in CI tools.

```
# --------------[HELMWAVE PROPERTIES]-----------------------

HELMWAVE_TEMPLATER=gomplate
HELMWAVE_LOG_FORMAT=pad
HELMWAVE_LOG_LEVEL=info
HELMWAVE_LOG_COLOR=true
HELMWAVE_AUTO_BUILD=true
HELMWAVE_KUBEDOG_ENABLED=true
HELMWAVE_KUBEDOG_STATUS_INTERVAL=-1s
HELMWAVE_AUTO_YML=true
HELMWAVE_GRAPH_WIDTH=1
```

So for example my file looks like this and in my CI, I just have to do `helmwave up` and `helmwave down`

> Unexpected behavior when somebody needs to define env variables.

Generally all the applications that does support .env, users are well aware of the priority and even this is something that can be documented. env variable defined by used exlictly is always given more priorty than .env files


However yes we can discuss on how it can be better implemented, if there are any doubts. The main reason this support would be good is because, one doesn't require an extra tool or hack or a way to be able to pass env to their helmwave app when they are in a folder with the respective .env file voila it applies like that, when they move to different project or folder it changes again consistenlty.

These .env values can also be used to supply values from env to the values.yaml files in gotmplates as well, a single source of data truth actually.

**Comment by zhilyaev** [comment]
I used to exec next script for similar purposes.

```bash
#!/usr/bin/env bash

export HELMWAVE_TAGS="postgresql,redis"
export HELMWAVE_LOG_LVL="DEBUG"


helmwave "$@"
```

**Comment by zhilyaev** [comment]
or 

```bash
export $(xargs < .env)
helmwave up
```

**Comment by anuragagarwal561994** [comment]
Yes the first approach will work, but it is not an integrated solution. Like one will have to create another file over a binary. But it is still a better solution.

In the second solution we are polluting a user environment for running the current program and adds an extra setup whenever we are switching projects or make a slight change in the env variables.

Suggestions from a user perspective :P

If we are just thinking from the perspective of running it finally then the above approaches seems like not a big deal, but think about when we are developing changes.

Every env variable we integrate in our values file with {{ getenv "ENV_VAR" }} we have to edit the .env file and do this manual step everytime which is polluting the env. Like by pollution here I mean, lets say I have added an env thats not an issue but if I have removed an environement, then I have to either reset my shell or there are other approaches but from the end user perspective it becomes painful.

**Comment by zhilyaev** [comment]
I need a little time to think

**Comment by anuragagarwal561994** [comment]
Appreciate the discussion and thanks for merging the changes 🙂

**Pull request merged**
