### PR TITLE
Fixed Test cases and Adds ChangeLogs for release 0.32.2

### PR DESCRIPTION
**Pull request by anuragagarwal561994**
Adds Chagelog

Fixes test cases and adds new functionalities after upgrading to helm 3.13.0

### CODE REVIEW

**Comment by zhilyaev** [comment]
Thanks 😊 
But it is not required. We are using 'changie' for automation these procedures.

**Comment by anuragagarwal561994** [comment]
Oh I got notification on my mail saying that I need to add this, although I used changie as well. Got to learn a new tool :P

Anyways I have fixed the test cases that were failing earlier after upgrading to helm 3.13.0

**Comment by anuragagarwal561994** [comment]
@zhilyaev let me know if something else is to be done in this

**Comment by anuragagarwal561994** [comment]
Added the changes in https://github.com/helmwave/helmwave/pull/762

**Pull request closed without merging**
